export const LOAD_MOVIES = "LOAD_MOVIES";
export const LOAD_MOVIES_FAVORIES = "LOAD_MOVIES_FAVORIES";
export const LOAD_ONE_MOVIE_BY_ID = "LOAD_ONE_MOVIE_BY_ID";
export const LOAD_MOVIES_RANDOM = "LOAD_MOVIES_RANDOM";
export const LOAD_MOVIES_SEARCH_BY_QUERY = "LOAD_MOVIES_SEARCH_BY_QUERY";
